name = "echo-novel"
account_id = "de7ecb0eaa0a328071255d557a6adb66"
compatibility_date = "2025-04-01"
workers_dev = true

routes = [
  { pattern = "echo-novel.innei.in", custom_domain = true, zone_name = "innei.in" }
]

[assets]
directory = "./dist"
not_found_handling = "404-page"

[observability]
enabled = true
